spring.application.name=rocmovies
server.port=9090
server.servlet.context-path=/rocmovies
server.error.include-message=always
server.error.include-binding-errors=always
spring.datasource.url=jdbc:mysql://192.168.231.130:3306/rocmovies
spring.datasource.username=valet
spring.datasource.password=valet
spring.jpa.hibernate.ddl-auto=update